- name: bootstrap rbpi
  hosts: localhost

  tasks:
  - name: install python3
    apt:
      name: python3
  - name: add grafana gpg
    apt_key:
      url: https://packages.grafana.com/gpg.key
  - name: grafana
    apt:
      name: grafana
  - name: prometheus
    apt:
      name: prometheus