- name: bootstrap rbpi
  hosts: localhost

  tasks:
  - name: install python3
    apt:
      name: python3

  - name: add grafana gpg
    apt_key:
      url: https://packages.grafana.com/gpg.key
  - name: add grafana repo
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
  - name: grafana
    apt:
      name: grafana

  - name: prometheus
    apt:
      name: prometheus

  - name: enable grafana
    systemd:
      enabled: yes
      name: grafana-server
      state: started

  - name: enabled prometheus
    systemd:
      enabled: yes
      name: prometheus
      state: started

  - name: mkdir ansible temp
    file:
      path: /tmp/ansible-blackbox
      state: directory

  - name: wget blackbox exporter
    get_url:
      url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.21.1/blackbox_exporter-0.21.1.linux-arm64.tar.gz
      dest: /tmp/ansible-blackbox/

  - name: unzip blackbox
    unarchive:
      dest: /bin/blackbox_exporter
      src: /tmp/ansible-blackbox/blackbox_exporter-0.21.1.linux-arm64.tar.gz