- name: bootstrap rbpi
  hosts: localhost

  tasks:
  - name: install python3
    apt:
      name: python3
  - name: grafana
    apt:
      name: grafana-server
  - name: prometheus
    apt:
      name: prometheus